[phases.setup]
nixPkgs = ["python312", "ffmpeg", "glib", "libGL", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
procfile = "Procfile"
