[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc", "ffmpeg", "glib", "libGL", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.start]
procfile = "Procfile"
